// THE ONE ICON VOCABULARY (2026-10-04): VS Code's own codicons, drawn from
// path data (codicon.ts, generated by scripts/gen-codicons.mjs) rather than the
// icon font — so an icon draws inside the tree's own `<svg>` as readily as in
// HTML chrome, and the static viewer, which loads no font, gets the same marks.
import { type CSSProperties } from "react";
import { CODICONS, type CodiconData, type CodiconName } from "./codicon";

/** One codicon, `size` px square (16, the size they are drawn for), filled in
 `color` (`currentColor` by default, so it takes its control's ink).

 In HTML it is a block-level `<svg>` (no baseline gap) that never shrinks in a
 flex row. Inside an `<svg>` pass `x`/`y` — the top-left corner in the parent's
 user space — and it nests as an `<svg>` element there. Hidden from assistive
 tech: the control it sits in carries the words (`aria-label`). */
export function Codicon({
  name,
  size = 16,
  x,
  y,
  color = "currentColor",
  opacity,
  style,
}: {
  name: CodiconName;
  size?: number;
  x?: number;
  y?: number;
  color?: string;
  opacity?: number;
  style?: CSSProperties;
}) {
  const icon: CodiconData = CODICONS[name];
  const inSvg = x !== undefined || y !== undefined;
  return (
    <svg
      data-ptw-codicon={name}
      x={x}
      y={y}
      width={size}
      height={size}
      viewBox={`0 0 ${icon.size} ${icon.size}`}
      fill={color}
      opacity={opacity}
      aria-hidden
      focusable="false"
      style={inSvg ? style : { display: "block", flex: "none", ...style }}
    >
      {icon.paths.map((p, i) => (
        <path
          key={i}
          d={p.d}
          fillRule={p.evenodd ? "evenodd" : undefined}
          clipRule={p.evenodd ? "evenodd" : undefined}
        />
      ))}
    </svg>
  );
}
