// THE ONE ICON VOCABULARY (2026-10-04): VS Code's own codicons, drawn from
// path data (codicon.ts, generated by scripts/gen-codicons.mjs) rather than the
// icon font — so an icon draws inside the tree's own `<svg>` as readily as in
// HTML chrome, and the static viewer, which loads no font, gets the same marks.
//
// It is also THE ICON SEAM of the appearance switch (appearance.ts): under
// `classic` the same semantic name draws the mark the chrome wore before the
// codicons (the drawn glyphs of 2026-09, restored from c709a11^), inside the
// same `size` box, so nothing measured around it moves. A name has ONE classic
// mark per SET: `chrome` (the status bar, its panels, the rail, the header,
// the message strip) and `node` (the hover bar and the `⋯` menu, where the same
// codicon names mean moves — `list-tree` is the outline layout in the bar and
// `⇑` on a node).
import { createElement as h, useContext, type CSSProperties, type ReactNode } from "react";
import { CODICONS, type CodiconData, type CodiconName } from "./codicon";
import { AppearanceContext } from "./appearance";
import { CHROME_RADIUS } from "./theme";

/** Which classic vocabulary a codicon name is read in (see the header). */
export type IconSet = "chrome" | "node";

/** One codicon, `size` px square (16, the size they are drawn for), filled in
 `color` (`currentColor` by default, so it takes its control's ink).

 In HTML it is a block-level `<svg>` (no baseline gap) that never shrinks in a
 flex row. Inside an `<svg>` pass `x`/`y` — the top-left corner in the parent's
 user space — and it nests as an `<svg>` element there. Hidden from assistive
 tech: the control it sits in carries the words (`aria-label`). */
export function Codicon({
  name,
  size = 16,
  x,
  y,
  color = "currentColor",
  opacity,
  style,
  set = "chrome",
}: {
  name: CodiconName;
  size?: number;
  x?: number;
  y?: number;
  color?: string;
  opacity?: number;
  style?: CSSProperties;
  set?: IconSet;
}) {
  const classic = useContext(AppearanceContext) === "classic";
  const inSvg = x !== undefined || y !== undefined;
  const css = inSvg ? style : { display: "block", flex: "none", ...style };
  const old = classic ? (set === "node" ? NODE_CLASSIC : CHROME_CLASSIC)[name] : undefined;
  if (old) {
    // The classic mark at its own pixel size, centred in the codicon's box:
    // the outer viewBox is the 16-unit codicon grid, scaled to `size`.
    return (
      <svg
        data-ptw-codicon={name}
        data-ptw-classic=""
        x={x}
        y={y}
        width={size}
        height={size}
        viewBox="0 0 16 16"
        opacity={opacity}
        aria-hidden
        focusable="false"
        style={{ ...css, color }}
      >
        {old}
      </svg>
    );
  }
  const icon: CodiconData = CODICONS[name];
  return (
    <svg
      data-ptw-codicon={name}
      x={x}
      y={y}
      width={size}
      height={size}
      viewBox={`0 0 ${icon.size} ${icon.size}`}
      fill={color}
      opacity={opacity}
      aria-hidden
      focusable="false"
      style={css}
    >
      {icon.paths.map((p, i) => (
        <path
          key={i}
          d={p.d}
          fillRule={p.evenodd ? "evenodd" : undefined}
          clipRule={p.evenodd ? "evenodd" : undefined}
        />
      ))}
    </svg>
  );
}

// ---------------------------------------------------------------------------
// THE CLASSIC MARKS, as they were drawn before 2026-10-04 (c709a11^: BarSvg's
// glyphs, the hover bar's drawn icons, menuIcons.ts's stroked paths, the rail's
// and the bar's text glyphs). Each sits centred in the 16-unit box.

/** The chrome's one stroke (`BAR_GLYPH_SW` before the codicons). */
const BAR_GLYPH_SW = 1.4;
/** The hover bar's and the `⋯` menu's drawn icons (`HOVER_ICON_SW`). */
const HOVER_ICON_SW = 0.9;

/** A drawn chrome mark `w`×`h` of ink (its own `viewBox`), centred, stroked in
 `currentColor` at the chrome's stroke with round caps and joins. */
const drawn = (w: number, h_: number, kids: ReactNode, viewBox?: string): ReactNode =>
  h(
    "svg",
    {
      x: (16 - w) / 2,
      y: (16 - h_) / 2,
      width: w,
      height: h_,
      viewBox: viewBox ?? `0 0 ${w} ${h_}`,
      fill: "none",
      stroke: "currentColor",
      strokeWidth: BAR_GLYPH_SW,
      strokeLinecap: "round",
      strokeLinejoin: "round",
      overflow: "visible",
    },
    kids,
  );

/** A text glyph centred in the box (the rail's `+ − ⛶`, `⚑`, `?`, the hover
 bar's `» ◎ ⊹ ⁇ ⇓ ⇑ ✎ ⧉ ⋯`), in the face it was set in. */
const glyph = (text: string, px = 13, font = "monospace"): ReactNode =>
  h(
    "text",
    {
      x: 8,
      y: 8,
      textAnchor: "middle",
      dominantBaseline: "central",
      fontSize: px,
      fontFamily: font,
      fill: "currentColor",
    },
    text,
  );

/** A hover-bar / menu icon on the old `-7 -7 14 14` grid (`HOVER_ICON_SW`),
 centred in the 16-unit box. */
const hover = (...kids: ReactNode[]): ReactNode =>
  h(
    "g",
    {
      transform: "translate(8 8)",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: HOVER_ICON_SW,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    ...kids,
  );
const p = (d: string, extra?: object): ReactNode => h("path", { d, ...extra });
const rx = CHROME_RADIUS - 1;
const box = h("rect", { x: -4.5, y: -4.5, width: 9, height: 9, rx });
const tab = (extra?: object): ReactNode =>
  h("rect", { x: -4.5, y: -2.5, width: 9, height: 5, rx, ...extra });

// The four layout marks (`LayoutGlyph`, 12×10).
const layoutMark = (d: string) => drawn(12, 10, p(d));
// `LayoutExtraGlyph`, 12×10.
const sideBySide = drawn(12, 10, [
  h("rect", { key: 1, x: 1.8, y: 1.3, width: 3.4, height: 7.4, rx: 0.6 }),
  h("rect", { key: 2, x: 6.8, y: 1.3, width: 3.4, height: 7.4, rx: 0.6 }),
]);
const gallery = drawn(12, 10, [
  h("rect", { key: 1, x: 3.6, y: 1.3, width: 4.8, height: 7.4, rx: 0.6 }),
  p("M1.9 3.6 0.8 5 1.9 6.4M10.1 3.6 11.2 5 10.1 6.4", { key: 2 }),
]);
// `CommentGlyph`, 12×11: the bubble and its tail, and what the mode adds.
const bubble = (extra: string, dots = false) =>
  drawn(12, 11, [
    h("rect", { key: "b", x: 1, y: 1, width: 10, height: 7, rx: 2 }),
    p(`M3.5 8v2.2l2.4-2.2${extra}`, { key: "t" }),
    dots &&
      h(
        "g",
        { key: "d", fill: "currentColor", stroke: "none" },
        h("circle", { cx: 6, cy: 3, r: 0.8 }),
        h("circle", { cx: 4.3, cy: 5.6, r: 0.8 }),
        h("circle", { cx: 7.7, cy: 5.6, r: 0.8 }),
      ),
  ]);
// `HeaderChevron` / `DisclosureGlyph` (8×5) and `ChevronGlyph` (6×8).
const m = BAR_GLYPH_SW / 2;
const chevDown = drawn(8, 5, p(`M${m} ${m}L4 ${5 - m}L${8 - m} ${m}`));
const chevUp = drawn(8, 5, p(`M${m} ${5 - m}L4 ${m}L${8 - m} ${5 - m}`));
const chevPrev = drawn(6, 8, p("M4.5 1L1.5 4L4.5 7"));
const chevNext = drawn(6, 8, p("M1.5 1L4.5 4L1.5 7"));
// The message strip's close, and every other `×` the chrome drew.
const cross = drawn(8, 8, p("M1 1L7 7M7 1L1 7"));

const CHROME_CLASSIC: Partial<Record<CodiconName, ReactNode>> = {
  "list-tree": layoutMark("M2.6 1.3v7.4M2.6 1.3h7.2M2.6 5h5"),
  "layout-sidebar-left": layoutMark("M2.2 1.3v7.4M2.2 5h6.3"),
  layout: layoutMark("M3.2 1.3v7.4M8.8 1.3v7.4"),
  "type-hierarchy-super": layoutMark("M6 1.3v2.9M6 4.2 2.2 8.7M6 4.2 9.8 8.7"),
  "split-horizontal": sideBySide,
  // Side-by-side's own icon since 2026-10-05 (the lens keeps
  // `split-horizontal`): the same classic mark.
  "layout-centered": sideBySide,
  window: gallery,
  "word-wrap": drawn(12, 10, p("M1.5 2h9M1.5 5h6.4M1.5 8h3.4")),
  comment: bubble("M3.7 3.4h4.6M3.7 5.6h2.6"),
  "eye-closed": bubble("M1.4 10.2 10.6 0.8"),
  sparkle: bubble("", true),
  // Narrate's own icon since 2026-10-05 (`sparkle` is the model's): the
  // classic narrate bubble.
  quote: bubble("", true),
  "comment-discussion": drawn(12, 11, [
    h("rect", { key: 1, x: 0.8, y: 0.8, width: 10.4, height: 9.4, rx: 1.6 }),
    h("rect", { key: 2, x: 3, y: 2.6, width: 6, height: 3.2, rx: 1 }),
    p("M4.4 5.8v1.4l1.4-1.4", { key: 3 }),
  ]),
  eye: drawn(
    14,
    10,
    [
      p("M1.4 8C3 5.4 5.3 4.1 8 4.1S13 5.4 14.6 8C13 10.6 10.7 11.9 8 11.9S3 10.6 1.4 8Z", { key: 1 }),
      h("circle", { key: 2, cx: 8, cy: 8, r: 1.9 }),
    ],
    "1 3 14 10",
  ),
  "chevron-down": chevDown,
  "chevron-up": chevUp,
  "chevron-left": chevPrev,
  "chevron-right": chevNext,
  "arrow-down": chevNext,
  "arrow-up": chevPrev,
  close: cross,
  question: glyph("?", 12, "inherit"),
  bookmark: glyph("⚑", 12),
  // `DiagGlyph`, 10×10.
  error: drawn(10, 10, p("M1.8 1.8L8.2 8.2M8.2 1.8L1.8 8.2")),
  warning: drawn(10, 10, [p("M5 1L9.2 8.8H0.8Z", { key: 1 }), p("M5 4v2", { key: 2 })]),
  info: drawn(10, 10, p("M5 0.9L9.1 5L5 9.1L0.9 5Z")),
  // The rail's text glyphs (and ⌥'s `⊞`/`⊟`, now their own buttons).
  "zoom-in": glyph("+", 14),
  "zoom-out": glyph("−", 14),
  "screen-full": glyph("⛶", 14),
  "expand-all": glyph("⊞", 14),
  "collapse-all": glyph("⊟", 14),
  // Restart File (2026-10-05): a drawn open circle with an arrowhead, in the
  // chrome's stroke — the classic hand of the eye and the bubble.
  "debug-restart": drawn(12, 12, [
    p("M2.2 6A3.8 3.8 0 1 0 3.3 3.3", { key: 1 }),
    p("M3.3 0.9V3.3H5.7", { key: 2 }),
  ]),
};

// The hover bar's moves and the `⋯` menu's rows.
const NODE_CLASSIC: Partial<Record<CodiconName, ReactNode>> = {
  "go-to-file": glyph("»", 17),
  target: glyph("◎"),
  // `SkipIcon`: the axis break in miniature.
  "debug-step-over": hover(
    p("M0 -4.8 V-1.8 M0 1.8 V4.8", { key: 1 }),
    p("M-2.6 -0.6 L2.6 -3 M-2.6 3 L2.6 0.6", { key: 2 }),
  ),
  "git-commit": glyph("⊹", 15),
  // `TrashIcon`.
  trash: hover(
    p("M-4.3 -2.8 H4.3", { key: 1 }),
    p("M-1.5 -2.8 V-3.9 H1.5 V-2.8", { key: 2 }),
    p("M-3.2 -2.8 V3.6 H3.2 V-2.8", { key: 3 }),
    p("M-1.15 -0.8 V2", { key: 4 }),
    p("M1.15 -0.8 V2", { key: 5 }),
  ),
  references: glyph("⁇"),
  loading: glyph("…"),
  wand: glyph("⇓"),
  "list-unordered": glyph("⇑"),
  // `InlineIcon` (down) and its mirror (up).
  "fold-down": hover(
    p("M-3.8 -3.6 H-0.4 A2.6 2.6 0 0 1 2.2 -1 V3.6", { key: 1 }),
    p("M0.6 2 L2.2 3.6 L3.8 2", { key: 2 }),
  ),
  "fold-up": h(
    "g",
    { transform: "translate(0 16) scale(1 -1)" },
    hover(
      p("M-3.8 -3.6 H-0.4 A2.6 2.6 0 0 1 2.2 -1 V3.6", { key: 1 }),
      p("M0.6 2 L2.2 3.6 L3.8 2", { key: 2 }),
    ),
  ),
  "lightbulb-autofix": glyph("✎"),
  // The lightbulb slot (batch 4) never existed in the old skin: drawn in the
  // stroked hand of `TrashIcon` — a bulb, its neck and two thread lines.
  lightbulb: hover(
    p("M-1.6 2.4 C-1.6 0.9 -3.6 0.2 -3.6 -1.9 A3.6 3.6 0 0 1 3.6 -1.9 C3.6 0.2 1.6 0.9 1.6 2.4 Z", { key: 1 }),
    p("M-1.4 3.9 H1.4", { key: 2 }),
    p("M-0.9 5.2 H0.9", { key: 3 }),
  ),
  // D6's "Ask the model" row: a four-point star, the polish line's cousin.
  sparkle: glyph("✦", 12),
  "split-horizontal": glyph("⧉"),
  ellipsis: glyph("⋯"),
  // menuIcons.ts's stroked rows.
  add: hover(box, p("M-2 0H2M0 -2V2")),
  // A ledger's "show / hide every step's goal" and a row's `+` (2026-10-05:
  // `unfold`/`fold`, which `add`/`remove` stood in for).
  unfold: hover(box, p("M-2 0H2M0 -2V2")),
  fold: hover(box, p("M-2 0H2")),
  "chevron-down": hover(box, p("M-2 0H2")),
  "chevron-right": hover(box, p("M-2 0H2M0 -2V2")),
  edit: hover(p("M-3.5 4L-3 1.4L2.4 -4L4 -2.4L-1.4 3ZM1 -2.6L2.6 -1")),
  comment: hover(p("M-4.5 -3.5H4.5V2H-0.5L-3 4.2V2H-4.5Z")),
  bookmark: hover(tab({ strokeDasharray: "2 1.6" })),
  close: hover(tab(), p("M-3.5 3.5L3.5 -3.5")),
  // `PinIcon` (12×12), filled when on.
  pin: h(
    "g",
    { transform: "translate(2 2)" },
    p("M4 1.5h4M4.8 1.5v3.2L3 7h6L7.2 4.7V1.5M6 7v3.8", {
      fill: "none",
      stroke: "currentColor",
      strokeWidth: HOVER_ICON_SW,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    }),
  ),
  pinned: h(
    "g",
    { transform: "translate(2 2)" },
    p("M4 1.5h4M4.8 1.5v3.2L3 7h6L7.2 4.7V1.5M6 7v3.8", {
      key: 1,
      fill: "none",
      stroke: "currentColor",
      strokeWidth: HOVER_ICON_SW,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    }),
    p("M4.8 1.5v3.2L3 7h6L7.2 4.7V1.5z", { key: 2, fill: "currentColor" }),
  ),
};
